language: java
jdk:
  - oraclejdk8
  
addons:
  artifacts: true
    paths:
    - $(ls target/*.jar | tr "\n" ":")
  s3_region: "us-west-2"

after_success:
  - mvn clean cobertura:cobertura coveralls:report
