language: java
jdk:
  - oraclejdk8
  
addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
    -  ./target/*.jar
    target_paths: builds/$TRAVIS_BRANCH/$TRAVIS_BUILD_NUMBER

after_success:
  - mvn cobertura:cobertura coveralls:report
